# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [217]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config

1.21.6


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(x.size)
print(x.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f5bf6328410>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v=np.arange(10,49)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
m=np.arange(0,9)
x=m.reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
x

array([[[0.32, 0.48, 0.2 ],
        [0.82, 0.3 , 0.91],
        [0.55, 0.75, 0.87]],

       [[0.87, 0.53, 0.87],
        [0.2 , 0.71, 0.52],
        [0.56, 0.2 , 0.26]],

       [[0.64, 0.49, 0.11],
        [0.7 , 0.46, 0.65],
        [0.72, 0.22, 0.65]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
print(x.min() , x.max())

0.004844352196906487 0.9980287887432499


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x=np.random.rand(30)
np.mean(x,axis=0)

0.4569136975336882

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((4,4))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x=np.ones((4,4))
x=np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
d=np.diag([1,2,3,4],k=-1)
d

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x=np.tile([[0,1],[1,0]],(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.rand(5,5)
mi=x.min()
ma=x.max()
new=(x-mi)/(ma-mi)
new

array([[0.02, 0.83, 0.61, 0.04, 0.26],
       [0.1 , 0.47, 0.69, 1.  , 0.81],
       [0.85, 0.  , 0.17, 0.24, 0.42],
       [0.85, 0.37, 0.63, 0.17, 0.45],
       [0.82, 0.54, 0.12, 0.23, 1.  ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color=np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.random.rand(5,3)
b=np.random.rand(3,2)
print(a@b)
#print(np.dot(a,b))

[[1.08 1.32]
 [1.04 1.36]
 [1.34 1.51]
 [1.2  1.72]
 [1.43 1.87]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x=np.arange(11)
x[(x>3) & (x<=8)]*= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
z= np.arange(11)
for i in range(3,9):
    z[i]=-z[i]
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: ignored

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#Legal expressions:
# 2<< Z >>2
# Z <- Z
# 1j*Z
# Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a=np.random.uniform(1,10,12)
a
b=np.ceil(a)
np.copysign(b,a)

array([ 2.,  4.,  4.,  2.,  4.,  5.,  4.,  5.,  5.,  4., 10.,  7.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,10,10)
x2= np.random.randint(5,15,10)
np.intersect1d(x1,x2)

array([], dtype=int64)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
ignore1=np.seterr(all='ignore')
np.arange(3)/0.


with np.errstate(divide='ignore'):
  print(np.arange(3)/0.)

[nan inf inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today','D')
yesterday = np.datetime64('today','D')-np.timedelta64(1, 'D')
tomorrow = np.datetime64('today','D')+np.timedelta64(1, 'D')
print('today: ',today)
print('yesterday: ',yesterday)
print('tomorrow: ',tomorrow)

today:  2022-11-05
yesterday:  2022-11-04
tomorrow:  2022-11-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x=np.arange('2016-07-01','2016-08-01',dtype = 'datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
x= np.random.rand(3,3)
y= np.random.rand(3,3)
np.add(x,y,out=y)
np.divide(x,2,out=x)
np.negative(x,out=x)
np.multiply(x,y,out=x)

array([[-0.75, -0.02, -0.28],
       [-0.11, -0.13, -0.15],
       [-0.03, -0.66, -0.64]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x=np.random.uniform(1,10,5)
print(x-(x%1))
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.trunc(x))

[3. 4. 2. 9. 9.]
[3. 4. 2. 9. 9.]
[ 4.  5.  3. 10. 10.]
[3 4 2 9 9]
[3. 4. 2. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x=np.zeros((5,5))
x+np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for i in range(10):
    yield i
x=np.fromiter(generator(),int)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x=np.linspace(0,1,11,endpoint=False)
x[1:]

array([0.09, 0.18, 0.27, 0.36, 0.45, 0.55, 0.64, 0.73, 0.82, 0.91])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.rand(10)
x.sort()
x

array([0.14, 0.2 , 0.29, 0.4 , 0.41, 0.54, 0.68, 0.8 , 0.89, 1.  ])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x=np.random.rand(5)
np.add.reduce(x)

1.6335354994024247

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.random(3)
B=np.random.random(3)
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x=np.ones(5)
x.flags.writeable=False
x

array([1., 1., 1., 1., 1.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x= np.random.random((10,2))
x1,y1 = x[:,0],x[:,1]
r=np.sqrt(x1**2+y1**2)
tita=np.arctan2(y1,x1)
print(r)
print(tita)

[1.08 0.79 0.32 0.67 0.85 0.98 1.14 1.15 0.59 1.03]
[0.53 0.78 0.9  1.3  0.06 1.24 0.57 0.65 0.6  0.62]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.random(10)
x[x.argmax()] = 0
x

array([0.66, 0.69, 0.  , 0.62, 0.33, 0.38, 0.78, 0.77, 0.38, 0.02])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x=9*(np.ones(5))
y=2*(np.ones(5))
v=np.subtract.outer(x,y)
c=1/v
c

array([[0.14, 0.14, 0.14, 0.14, 0.14],
       [0.14, 0.14, 0.14, 0.14, 0.14],
       [0.14, 0.14, 0.14, 0.14, 0.14],
       [0.14, 0.14, 0.14, 0.14, 0.14],
       [0.14, 0.14, 0.14, 0.14, 0.14]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print('-------------------------')
print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print(np.finfo(np.float32).eps)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)
print(np.finfo(np.float64).eps)

-32768
32767
-2147483648
2147483647
-------------------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize,precision=2)
x=np.random.random((5,5))
x

array([[0.57, 0.59, 0.96, 0.59, 0.03],
       [0.38, 0.75, 0.54, 0.79, 0.59],
       [0.71, 0.19, 0.69, 0.69, 0.29],
       [0.17, 0.29, 0.17, 0.46, 0.23],
       [0.06, 0.66, 0.05, 0.89, 0.43]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x=np.arange(100)
v=np.random.uniform(0,100)
sub=np.abs(x-v)
x[sub.argmin()]

50

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x=np.zeros(10,[('position',[ ('x', float, 1),('y', float, 1)]),('color',[ ('r', float, 1),('g', float, 1),('b', float, 1)])])
x

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
x = np.random.random((100,2))
x1,y1 = np.atleast_2d(x[:,0], x[:,1])
np.sqrt( (x1-x1.T)**2 + (y1-y1.T)**2)

array([[0.  , 0.63, 0.54, 0.5 , 0.89, 0.26, 0.36, 0.41, 0.66, 0.37, 0.85,
        0.4 , 0.4 , 0.96, 0.73, 0.43, 0.68, 0.52, 0.68, 0.6 , 0.53, 0.81,
        0.49, 0.66, 0.56, 0.61, 0.28, 0.76, 0.44, 0.33, 0.63, 0.79, 0.43,
        0.8 , 0.47, 0.63, 0.82, 0.89, 0.55, 0.52, 0.86, 0.72, 0.55, 0.62,
        0.53, 0.26, 0.78, 0.57, 0.75, 0.44, 0.82, 0.88, 0.22, 0.66, 0.91,
        0.98, 0.83, 0.5 , 0.53, 0.19, 0.38, 0.37, 0.47, 0.28, 0.24, 1.12,
        0.89, 0.35, 0.62, 0.31, 0.58, 0.62, 0.15, 1.03, 0.67, 0.74, 0.53,
        0.43, 0.97, 0.74, 0.25, 0.26, 0.89, 0.33, 0.74, 0.43, 0.54, 0.73,
        0.84, 0.69, 0.74, 0.47, 0.94, 0.41, 0.88, 0.54, 0.89, 0.75, 1.02,
        0.94],
       [0.63, 0.  , 0.55, 0.58, 0.33, 0.4 , 0.28, 0.7 , 0.12, 0.28, 0.23,
        0.45, 0.58, 0.37, 0.44, 0.27, 0.52, 0.66, 0.42, 0.48, 0.47, 0.55,
        0.68, 0.29, 0.52, 0.34, 0.81, 0.35, 0.56, 0.57, 0.35, 0.56, 0.4 ,
        0.2 , 0.54, 0.65, 0.27, 0.4 , 0.63, 0.39, 0.33, 0.33, 0.49, 0.1 ,
        0.13, 0.68, 0.1

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x= np.arange(5, dtype='float32')
x=x.astype('int32', copy=False)
x

array([0, 1, 2, 3, 4], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
s1="1,2,3, 4, 5"
s2="6, , , 7, 8"
s3=" , ,9,10,11"
x=np.genfromtxt([s1,s2,s3], delimiter=",", dtype='int')
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x=np.random.random((3,3))
for i,j in np.ndenumerate(x):
  print(i,j)
print('____________________')
for i in np.ndindex(x.shape):
  print(i,x[i])

(0, 0) 0.3869546833711779
(0, 1) 0.9527496240173446
(0, 2) 0.6955810880261487
(1, 0) 0.92105466704577
(1, 1) 0.10703306127277823
(1, 2) 0.8444248666989509
(2, 0) 0.5229673901839782
(2, 1) 0.5696168141246356
(2, 2) 0.9981840128678884
____________________
(0, 0) 0.3869546833711779
(0, 1) 0.9527496240173446
(0, 2) 0.6955810880261487
(1, 0) 0.92105466704577
(1, 1) 0.10703306127277823
(1, 2) 0.8444248666989509
(2, 0) 0.5229673901839782
(2, 1) 0.5696168141246356
(2, 2) 0.9981840128678884


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x=np.linspace(0,5,110)
y=np.linspace(5,10,10)
X,Y=np.meshgrid(x,y)
Z=X+Y
np.exp(Y)

array([[  148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41,   148.41,   148.41,
          148.41,   148.41,   148.41,   148.41, 

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=5
p=3
x=np.ones((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),6)
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 6., 1., 1., 1.],
       [1., 6., 1., 6., 1.],
       [1., 1., 1., 1., 1.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x=np.random.rand(3,3)
mean=x.mean(axis=1,keepdims=True)
y=x-mean
y

array([[ 0.16,  0.25, -0.41],
       [ 0.  ,  0.07, -0.07],
       [ 0.21, -0.05, -0.15]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x=np.random.randint(0,10,(3,3))
x[x[:,1].argsort()]

array([[4, 3, 4],
       [9, 6, 7],
       [3, 9, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x=np.random.randn(3,3)
(~x.any(axis=0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x= np.random.uniform(0,1,10)
v= 0.2
n= x.flat[np.abs(x-v).argmin()]
n

0.2222498772295748

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x=np.random.rand(3,1)
y=np.random.rand(1,3)
iterator=np.nditer([x,y,None])
for x,y,z in iterator:
    z[...]=x+y
iterator.operands[2]

array([[0.84, 1.65, 0.85],
       [0.45, 1.26, 0.46],
       [0.59, 1.4 , 0.6 ]])

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a =np.array([1,2,3,4])
b= np.array([0,1,2,3])
np.add.at(a,b,1)
print(a)

[2 3 4 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x=np.array([1,2,3,4,5,6])
I=[1,3,9,3,4,1]
F=np.bincount(I,x)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x=np.random.rand(3,4,3,4)
x.sum(axis=(-2,-1))

array([[7.23, 5.94, 8.02, 7.18],
       [6.37, 6.24, 6.04, 4.57],
       [6.68, 6.75, 4.7 , 6.49]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D=np.random.uniform(0,1,50)
S=np.random.randint(0,5,50)
bin1= np.bincount(S, weights=D)
bin2 = np.bincount(S)
mean = bin1/bin2
mean

array([0.45, 0.6 , 0.46, 0.49, 0.5 ])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a=np.random.random((3,3))
b=np.random.random((3,3))
prod=np.dot(a,b)
np.diag(prod)

array([0.33, 0.66, 1.04])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
v=np.array([1,2,3,4,5])
n=3
new = np.zeros(len(v) + (len(v)-1)*(n))
new[::4]=v
new

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a=np.random.random((5,5,3))
b=np.random.random((5,5))
a*b[:,:,None]

array([[[0.09, 0.06, 0.04],
        [0.27, 0.41, 0.17],
        [0.25, 0.38, 0.36],
        [0.16, 0.09, 0.19],
        [0.41, 0.41, 0.49]],

       [[0.02, 0.  , 0.06],
        [0.01, 0.02, 0.02],
        [0.11, 0.11, 0.06],
        [0.01, 0.  , 0.15],
        [0.54, 0.4 , 0.38]],

       [[0.05, 0.43, 0.2 ],
        [0.32, 0.05, 0.73],
        [0.  , 0.  , 0.03],
        [0.9 , 0.68, 0.77],
        [0.06, 0.  , 0.83]],

       [[0.34, 0.4 , 0.13],
        [0.01, 0.  , 0.  ],
        [0.44, 0.34, 0.43],
        [0.25, 0.49, 0.34],
        [0.1 , 0.06, 0.33]],

       [[0.29, 0.32, 0.66],
        [0.16, 0.52, 0.3 ],
        [0.53, 0.48, 0.57],
        [0.37, 0.5 , 0.52],
        [0.02, 0.01, 0.04]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a=np.random.rand(3,3)
a[[0,1]]=a[[1,0]]
a

array([[0.81, 0.47, 0.38],
       [0.5 , 0.61, 0.86],
       [0.63, 0.77, 0.11]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C=np.bincount([1,2,5,6,3,2])
A=np.repeat(np.arange(len(C)),C)
A

array([1, 2, 2, 3, 5, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
x=np.arange(20)
sum=np.cumsum(x)
avg=sum/3
avg

array([ 0.  ,  0.33,  1.  ,  2.  ,  3.33,  5.  ,  7.  ,  9.33, 12.  ,
       15.  , 18.33, 22.  , 26.  , 30.33, 35.  , 40.  , 45.33, 51.  ,
       57.  , 63.33])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
a=np.arange(10)
size=a.itemsize
step=3
stride_tricks.as_strided(a, shape=(a.size-step+1,step),strides=(size,size))

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
a=np.arange(10)
a.itemsize

8

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x=np.random.uniform(1,2,10)
y=np.logical_not(x,out=x)
print(y)
x1=np.random.uniform(1,3,10)
y1=np.negative(x1,out=x1)
print(y1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-1.25 -1.42 -2.84 -2.76 -1.69 -2.5  -2.01 -1.95 -2.78 -1.98]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib.stride_tricks import as_strided
Z=np.arange(1,15,dtype=np.uint32)
R=as_strided(Z,(11,4),(4,4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
x=np.random.uniform(0,5,(5,5))
np.linalg.matrix_rank(x)

5

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x=np.random.randint(0,10,50)
bin1=np.bincount(Z)
bin1.argmax()

1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.uniform(0,10,(10,10))
C = as_strided(Z, shape=(3,3),strides=Z.strides)
print(C)

[[6.61 9.61 6.93]
 [5.68 8.24 1.74]
 [0.8  3.57 6.14]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p=4
n=3
mat1= np.zeros((p,n,n))
vec1= np.zeros((p,n,1))
np.tensordot(mat1,vec1, axes=[[0, 2], [0, 1]])


array([[0.],
       [0.],
       [0.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x=np.ones((16,16))
b=4
s=np.add.reduceat(np.add.reduceat(x,np.arange(0, x.shape[0], b), axis=0),np.arange(0, x.shape[1], b), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
x=np.linspace(1,100,100)
n=10
x[np.argsort(x)[-n:]]

array([ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
x=np.array([('Anoop',22,'pass'),('Randy',25,'fail')])
np.core.records.fromarrays(x.T,names='a,b,c',dtype=np.dtype([('a','S3'),('b',np.int32),('c','S3')]))

rec.array([(b'Ano', 22, b'pas'), (b'Ran', 25, b'fai')],
          dtype=[('a', 'S3'), ('b', '<i4'), ('c', 'S3')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x=np.random.rand(100,100)
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i',x,x,x))

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
np.where(C.any((3,1)).all(1))[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
x= np.array([5,1,2,6,4,55],dtype=uint8)
y=np.unpackbits(x)
y

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
m=np.random.randint(0,4,(5,5))
c=np.ascontiguousarray(m)
_,y= np.unique(c,return_index=True)
m[y]

IndexError: ignored

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
x=np.random.uniform(0,5,10)
y=np.random.uniform(5,10,10)
print(np.einsum('i->i',x))
print(np.einsum('i,i',x,y))
print(np.einsum('i->',y))
print(np.einsum('i,i->i',x,y))

[4.97 3.98 2.77 3.83 2.88 0.53 0.61 4.69 3.06 2.75]
216.43082880051844
74.6833719915769
[33.42 29.58 14.78 32.81 20.69  5.2   5.05 32.65 25.42 16.83]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
x= np.array([[5,2,4,5,4],[8,65,5,52,7],[8,7,6,4,5]])
n = 3
m=np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
x[m][1,:]

array([ 8, 65,  5, 52,  7])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)